const words = [
  "apple",
  "banana",
  "cherry",
  "date",
  "elderberry",
  "fig",
  "grape",
  "honeydew",
  "kiwi",
  "lemon",
  "mango",
  "nectarine",
  "orange",
  "papaya",
  "quince",
  "raspberry",
  "strawberry",
  "tangerine",
  "ugli",
  "vanilla",
  "watermelon",
  "xigua",
  "yam",
  "zucchini",
  "apricot",
  "blueberry",
  "cantaloupe",
  "dragonfruit",
  "eggplant",
  "feijoa",
  "guava",
  "huckleberry",
  "imbe",
  "jackfruit",
  "kumquat",
  "lime",
  "mulberry",
  "naranjilla",
  "olive",
  "peach",
  "plum",
  "pomegranate",
  "quandong",
  "rambutan",
  "soursop",
  "tamarind",
  "ugni",
  "voavanga",
  "wolfberry",
  "ximenia",
  "yumberry",
  "ziziphus",
  "acerola",
  "bilberry",
  "cloudberry",
  "durian",
  "elderflower",
  "figs",
  "grapefruit",
  "hawthorn",
  "indian fig",
  "jabuticaba",
  "kiwano",
  "lemonade berry",
  "mangosteen",
  "nance",
  "osage-orange",
  "passionfruit",
  "quenepa",
  "rose apple",
  "sapodilla",
  "tangelo",
  "ubajay",
  "velvet apple",
  "white sapote",
  "xylocarp",
  "yellow passionfruit",
  "zabergau",
  "abiu",
  "breadfruit",
  "cashew apple",
  "damson",
  "evergreen huckleberry",
  "finger lime",
  "gooseberry",
  "honeyberry",
  "illawarra plum",
  "jujube",
  "kakadu plum",
  "longan",
  "mamoncillo",
  "nannyberry",
  "ora-pro-nobis",
  "pitanga",
  "quenepa",
  "rata",
  "salak",
  "tamarillo",
  "urumqi",
  "viburnum",
];

function mergedStrings() {
  const wordsWithStrings = words.join(" ");
  return wordsWithStrings;
}

console.log(mergedStrings());
